name: goconcert
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: "3.7.0"

dependencies:
  camera: ^0.11.1
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_exif_rotation: ^0.5.1
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  google_ml_kit: ^0.20.0
  google_mlkit_text_recognition: ^0.15.0
  image: ^4.5.4
  image_picker: ^1.1.2
  nik_validator: ^1.1.2
  permission_handler: ^12.0.0+1
  provider: ^6.1.1
  barcode_widget: ^2.0.4

  firebase_analytics: ^11.4.5

  flutter_spinkit: ^5.1.0
  http: ^1.4.0


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/background.png
    - assets/img/chevron-left-solid.svg
    - assets/img/NewJeans-banner.png
    - assets/img/LeSserafim-banner.png
    - assets/img/Coldplay-banner.png
    - assets/img/bmth-banner.png
    - assets/img/singer.png
    - assets/img/bell.png
    - assets/img/search.png
    - assets/img/NewJeans.png
    - assets/img/LeSserafim.png
    - assets/img/bmth.jpeg
    - assets/img/coldplay.jpeg
    - assets/img/left-chevron.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.2
  material_color_utilities: ^0.12.0
  vector_math: ^2.1.5
  vm_service: ^15.0.0
  lints: ^6.0.0
